services:
  - type: web
    name: cyber-hax-v5
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server_main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
